module PAT.FHIR.Extensions

open PAT.FHIR.Urls

module KnownExtensions =
    let IndigenousStatus = "http://hl7.org.au/fhir/StructureDefinition/indigenous-status"

module PatExtensions =
    let urlFor s = patFhirUrl "extensions/" + s

    module Urls =
        // Extensions on resources imported from some Practice Management System (e.g. Patient, Condition)
        let PRACTICE_SOFTWARE_INTERNAL_ID = urlFor "source-practice-software-InternalId"
        let PRACTICE_SOFTWARE_CONTACT_ID = urlFor "source-practice-software-ContactId"
        let PRACTICE_SOFTWARE_RECORD_ID = urlFor "source-practice-software-RecordId"
        let BPCODE = urlFor "source-practice-software-BPCODE"
        let SOURCE_PRACTICE_SOFTWARE = urlFor "source-practice-software"
        let PAT_VERSION = urlFor "PAT-version"


        let ADHOC_PATIENT = urlFor "adhoc-patient"

        // For DataElement narrative images
        // Without an extension referencing it HAPI seems to drop the contained Binary resource
        // pointed to by the attachment
        // TODO: submit issue report? see FHIR spec narrative.html
        let CONTAINED_IMAGE = urlFor "Contained-Image"

        let QUESTION_TYPE = urlFor "Question-Type"

        // NOTE: Can have multiple CLINICAL_CATEGORY extensions
        let CLINICAL_CATEGORY = urlFor "Clinical-Category"

        let LAST_QUESTION = urlFor "Last-Question"
        let NA_BUTTON_TEXT = urlFor "NA-button-text"
        let DISPLAY_SETTINGS = urlFor "Display-Settings"

        // Questionnaire items - linked questions/test that can inform answer to a given question
        //    e.g. Cholesterol results when prompting to ensure they are adequately managed
        let LINKED_QUESTION = urlFor "Linked-Question"
        let LINKED_TEST     = urlFor "Linked-Test"


        module QuestionnaireResponse =
            // sort key relative to other QuestionnaireResponse(s) - used when combining them
            let SortKey = urlFor "Questionnaire-Response-Sort-Key"

            // Reference to the Condition(s) that have led to this QuestionnaireResponse to be generated by "auto-matching"
            let AutomatchedReason = urlFor "Questionnaire-Response-Automatched-Reason"


        // CarePlans
        let ActivityTriggeredBy = urlFor "Activity-Triggered-By"
        let ActivityAddedUnder = urlFor "Activity-Added-Under"
        let ActivityTriggeredButDeleted = urlFor "Activity-Triggered-But-Deleted"
        let CarePlanCreated = urlFor "CarePlan-Created"
        
        let AlliedHealthEPCMedicareVisitCount = urlFor "Allied-Health-EPC-Medicare-Visit-Count"

        // ContactPoint
        let ContactPointAfterHours = urlFor "After-Hours"

        module Encounter =
            let NeedsSubclinicSelection = urlFor "Needs-SubClinic-Selection"
            let LabResultsLoaded = urlFor "Lab-Results-Loaded"

        module ReferralRequest =
            let SecretToken = urlFor "Referral-Secret-Token"